### ISSUE TITLE
Create the first template

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-templates#1]
The first template should be very similar to the `HelloWorld` sample but just display a button and a label that gets updated when the button is tapped. Project hierarchy should be like Maven/Gradle (e.g. `src/main/java`). Set up a `resources/` folder with the default RoboVM icons and launch images. The package name and class name of the main class has to be changed to match the values entered by the user.

**Comment by BlueRiverInteractive** [comment]
Our first template (default) is now ready. It's a maven archetype but also has an assembly to package the template in a tar.gz without maven specific files to be used in the templater project.
