### ISSUE TITLE
Fix release-robovm-templates on build server

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-templates#3]
I'm not entirely sure the build job for releasing this project is correct. Also, check the poms, i'm not sure they way we reference the compiler is correct for a release.

**Comment by badlogic** [comment]
I added the following:
1. robovm-templates, snapshot builds
2. release-robovm-templates, release builds

The snapshot project is invoked at the end of the robovm snapshot build. It's also invoked as the first build step of robovm-eclipse, as it depends on robovm-templates.

The release project must be invoked manually, AFTER release-robovm, and BEFORE release-robovm-eclipse. I'm not sure if adding it as a build-step to release-robovm-eclipse is what we want in case something goes wrong.

**Comment by ntherning** [comment]
Works now.
