### ISSUE TITLE
Kotlin crossplatform app fails on IntelliJ IDEA 14.1.3 and AndroidStudio

### ISSUE THREAD

**Issue by intrigus** [robovm/robovm-templates#32]
The crossplatform kotlin app fails to build, with this error:
`Cannot change configuration ':classpath' after it has been resolved.`

RoboVM Plugin version is 1.11.0
Kotlin Plugin version is 1.0.0-beta-2423-IJ41-19

I would like to have more information for you :(

**Comment by badlogic** [comment]
Can you update to 15.0.1? I tested in 14.1.3 and AS 14 and did not see any
issues.

**Comment by intrigus** [comment]
I updated to 15.0.1, but I still can't run the android project. 
I changed the build scripts and now it seems to work. I'll post the changed scripts tomorrow, if you want.

**Comment by badlogic** [comment]
How does Android fail for you?

**Comment by intrigus** [comment]
I'm able to import the crossplatform kotlin project without problems, but I cannot execute android, fails with `Cannot change configuration ':classpath' after it has been resolved.`

I'll try it on another computer, if I have time...

**Comment by badlogic** [comment]
What does a cli build via Gradle say?

**Comment by badlogic** [comment]
OK, i can confirm the issue in 14.1.4
![http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202015-12-01%20at%2013.42.01-xAzIJVhs2z.png](http://libgdx.badlogicgames.com/uploads/Screen%20Shot%202015-12-01%20at%2013.42.01-xAzIJVhs2z.png)

**Comment by badlogic** [comment]
Seems like line 9 in the root `build.gradle` is the issue. That pulls in kotlin as a dependency for the build script (not the modules themselves).

**Comment by badlogic** [comment]
On IntelliJ IDEA 15.0.2 EAP is works as intended as well. Including running the Android project.

**Comment by badlogic** [comment]
This should be fixed in the latest snapshot build (1.11.1), the generated template will refrain from using allprojects.

**Comment by badlogic** [comment]
Importing into AS 14 also works as expected. Thanks for reporting!

**Comment by intrigus** [comment]
Amazing how fast you answered :)
Will try later (~2h)

**Comment by intrigus** [comment]
I can confirm that it works now :)
